spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/beauty_service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

mail:
  host: smtp.gmail.com
  port: 587
  username: woow.information@gmail.com
  password: Woow_desonex!!!
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

logging:
  level:
    root: info
    am.itspace: debug
  file:
    name: C:\\Users\\ArtPa\\IdeaProjects\\BeautySalon\\logs\\beauty-%d{yyyy-MM-dd-HH-mm-ss}.%i.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
